// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5NtTkfdPPg3VnzY2_DFALDnduuWmX6l4',
    appId: '1:992752067381:web:83eadd167c5d1a9207627c',
    messagingSenderId: '992752067381',
    projectId: 'todo-app-cc8ac',
    authDomain: 'todo-app-cc8ac.firebaseapp.com',
    storageBucket: 'todo-app-cc8ac.firebasestorage.app',
    measurementId: 'G-RXFZXNEP2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-zR_qxnbhDavIa23Gr_6HM5gWEd7Knhw',
    appId: '1:992752067381:android:1ac5f849461404b007627c',
    messagingSenderId: '992752067381',
    projectId: 'todo-app-cc8ac',
    storageBucket: 'todo-app-cc8ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKB3QTqL0qru7L8rKKkpNBZlMG3Laoj8',
    appId: '1:992752067381:ios:3b4ba1026b40aedf07627c',
    messagingSenderId: '992752067381',
    projectId: 'todo-app-cc8ac',
    storageBucket: 'todo-app-cc8ac.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeKB3QTqL0qru7L8rKKkpNBZlMG3Laoj8',
    appId: '1:992752067381:ios:3b4ba1026b40aedf07627c',
    messagingSenderId: '992752067381',
    projectId: 'todo-app-cc8ac',
    storageBucket: 'todo-app-cc8ac.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5NtTkfdPPg3VnzY2_DFALDnduuWmX6l4',
    appId: '1:992752067381:web:c2ff6bbcf94171e907627c',
    messagingSenderId: '992752067381',
    projectId: 'todo-app-cc8ac',
    authDomain: 'todo-app-cc8ac.firebaseapp.com',
    storageBucket: 'todo-app-cc8ac.firebasestorage.app',
    measurementId: 'G-5Q0WYPN5ZD',
  );
}
